### ISSUE TITLE
使用container-name参数，模糊匹配宿主机上的容器

### ISSUE THREAD

**Issue by lss9981** [chaosblade-io/chaosblade-exec-cri#2]
使用container-name参数，模糊匹配宿主机上的容器，可能会匹配到其他容器，比如注入redis，可能会注入到redisfilebeat，有无办法可以完全匹配。

**Comment by sanxun0325** [comment]
通过container-id也可以

**Comment by lss9981** [comment]
> 通过container-id也可以

**Comment by lss9981** [comment]
> 通过container-id也可以

目前由于一些不用无法拿到container-id，所以想问下后续有无完全匹配的想法

**Comment by xcaspar** [comment]
可以指定 `--container-name` 来指定容器，目前是通过 docker client ContainerList 函数获取的容器
