### ISSUE TITLE
支持containerd

### ISSUE THREAD

**Issue by beiketianzhuang** [chaosblade-io/chaosblade-exec-cri#5]
请问chaosblade的可以支持到containerd的容器注入吗

**Comment by xcaspar** [comment]
从 1.5.0 版本就开始支持了。

**Comment by beiketianzhuang** [comment]
> 从 1.5.0 版本就开始支持了。

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/23691253/174262821-00f81938-f857-40a5-97bc-2649566e70f2.png">
可是为啥我执行报错和docker相关

**Comment by beiketianzhuang** [comment]
> 从 1.5.0 版本就开始支持了。

我用的chaosblade是最新版本1.5.0

**Comment by xcaspar** [comment]
> 

添加 -h 看下用法

**Comment by xcaspar** [comment]
cc @MandssS

**Comment by beiketianzhuang** [comment]
> 从 1.5.0 版本就开始支持了。

可能我描述的不是很清晰，我的想使用的场景是在宿主机上对指定的containerd容器实现故障注入，通过制定容器id，可以对其jvm实现故障注入。

**Comment by MandssS** [comment]
我这边会下个版本中尽快处理

**Comment by beiketianzhuang** [comment]
> 



> 我这边会下个版本中尽快处理
感谢🙏

**Comment by MandssS** [comment]
麻烦可以使用最新的v1.6.1版本

并且，如果是containerd 容器运行时，container-id不能被截断，且需要加上参数 --container-runtime containerd 指明容器运行时

**Comment by beiketianzhuang** [comment]
> 麻烦可以使用最新的v1.6.1版本
> 
> 并且，如果是containerd 容器运行时，container-id不能被截断，且需要加上参数 --container-runtime containerd 指明容器运行时

好的感谢了，我今天试下感谢大佬的即使支持
